### ISSUE TITLE
plugin not found in packagist

### ISSUE THREAD

**Issue by lostfocus** [netresearch/deutschepost-module-autocomplete-sw6#4]
Hi,
we're trying to install the plugin like so: https://github.com/netresearch/deutschepost-module-autocomplete-sw6#from-packagist and it doesn't look like `netresearch/postdirekt-autocomplete` is a valid packagist name. 
Is it something we're missing?

**Comment by powli** [comment]
Hey @lostfocus,

it was actually our fault. Fixed that: https://packagist.org/packages/netresearch/postdirekt-autocomplete

**Comment by lostfocus** [comment]
Thanks a lot!
